apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort  # Peut aussi être LoadBalancer si supporté
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30007  # Si type: NodePort
