# Generated by Django 5.1.3 on 2024-11-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("date_add", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_add"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("prix", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="photos", verbose_name="My Photo"
                    ),
                ),
                ("image", models.CharField(max_length=5000)),
                ("date_add", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorie",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_add"],
            },
        ),
    ]
